# Azure account and batch service parameters
BATCH_ACCOUNT_NAME: '[YOUR_BATCH_ACCOUNT_NAME]'
BATCH_ACCOUNT_KEY: '[YOUR_BATCH_ACCOUNT_KEY]'
BATCH_ACCOUNT_URL: '[YOUR_BATCH_ACCOUNT_URL]'
STORAGE_ACCOUNT_NAME: '[YOUR_STORAGE_ACCOUNT_NAME]'
STORAGE_ACCOUNT_KEY: '[YOUR_STORAGE_ACCOUNT_KEY]'
POOL_ID: 'MultiObjectFiltersPool'
DEDICATED_POOL_NODE_COUNT: 3
LOW_PRIORITY_POOL_NODE_COUNT: 0
POOL_VM_SIZE: 'STANDARD_A1_v2'
JOB_ID: 'MultiObjectFiltersPoolJob'
NUMBER_OF_TASKS: 3
TIMEOUT_PERIOD: 120 # in minutes (time for the tasks to complete)
# Application parameters
APP_ID: 'multi-object-filters-demo'
APP_VERSION: '1.1.0'
APP_BINARY: 'demo.bin'
APP_ARGS: '-f phd cphd lccm -pd 0.95 -nt 15'
OUTPUT_DIR: 'results'
OUTPUT_FILENAME: 'results-{}.pkl'
